-include MakeFileI

clean:
	rm -f ../lpi ../lpi-server ../liblpi.cma
	rm -f $(OBJDIR)/*.cm*
	rm -f $(SRCDIR)/*.cm* $(SRCDIR)/*~
	rm -f $(SRCDIR)/parser.ml $(SRCDIR)/parser.mli $(SRCDIR)/lexer.ml

include $(OBJDIR)/.depend
